initial import
Zubax/Komar pull request #2
Opened 2020-04-10 09:33 UTC by j3qq4hch

2020-04-11 13:15 UTC, dimracer requested changes

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\input{communication interfaces}
```suggestion
\input{communication_interfaces}
```
В названиях файлов не должно быть пробелов.

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\input{led indication}
```suggestion
\input{led_indication}
```

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\input{mechanical characteristics}
```suggestion
\input{mechanical_characteristics}
```

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\input{motor selection}
```suggestion
\input{motor_selection}
```

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
Вообще-то это не так. Komar не поставляется в комплекте с мотором.

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +         Myxa B offers a doubly-redundant CAN bus interface for mission-critical applications.
просмотрели

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\includegraphics[width=0.6\textwidth]{figures/top view.png}
Давайте лучше поставим фото. С фото даташит смотрится живее. 
Фото есть в моей ветке.

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/characteristics.tex
> +    Phase current amplitude   &       & 130\tnote{a}    &   A            \\
Даже в лучшие времена защита обрубала фазный ток на отметке 93-95 А. Давайте хотя бы 100 А поставим.

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/characteristics.tex
> +    DC continuous current     &       & 90              &   A            \\
Давайте не будем соблазнять пользователя брать в руки калькулятор. Он там такого насчитает. Максимальный ток будет, очевидно, при минимальном напряжении 13 В. Амплитуда фазного напряжения при этом будет 6.5 В и амплитуда фазного тока 100 А (см. выше). Тогда имеем: Idc =  1.5 6.5 100 / 13 = **75**

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/Komar.tex
> +    \item 12 -- 51 V input voltage range (4 -- 12S $\text{LiCoO}_\text{2}$ battery).
```suggestion
    \item 13 -- 51 V input voltage range (4 -- 12S $\text{LiCoO}_\text{2}$ battery).
```

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/characteristics.tex
> +    Supply voltage                          & 12    &       & 51    & V               \\
```suggestion
    Supply voltage                          & 13    &       & 51    & V               \\
```

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/characteristics.tex
> +If the self-resistance of the power supply network is not sufficiently low, the regenerative energy transfer may lead to an increase of the supply voltage beyond the safe operating limits.
Длина строки. Пожалуйста, исправьте длину строки в других местах самостоятельно.

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/communication interfaces.tex
> +    CAN1 (2 connectors)     & JST SM04B-GHS     \\
Точно ли угловые разхемы стоят на комаре? Не прямые ли?

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/communication interfaces.tex
> +	2       & Input/Output & GPIO1     & RC PWM input/Thermistor input\\
```suggestion
	2       & Input/Output & GPIO1     & RC PWM input/Thermistor input \\
```

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/mechanical characteristics.tex
> +
Здесь - самое место для таблички с массо-габаритными и IP характеристиками.

2020-04-11 13:15 UTC, dimracer commented on docs/datasheet/overview.tex
> +12 –- 51 V (4 –- 12S $\text{LiCoO}_\text{2}$ battery).
```suggestion
13 -- 51 V (4 -- 12S $\text{LiCoO}_\text{2}$ battery). 
```

2020-04-11 13:22 UTC, dimracer requested changes

2020-04-11 13:22 UTC, dimracer commented on docs/datasheet/Komar.tex
> + any PMSM or BLDC motor as it is able to measure the parameters of the driven motor and automatically optimize
```suggestion
any PMSM or BLDC motor as it is able to measure the parameters of the driven motor and automatically optimize 
```

2020-04-11 13:22 UTC, dimracer commented on docs/datasheet/Komar.tex
> + itself for best performance. Komar is based on \mbox{mitochondrik} control module. All hardware is open source and available on Github\footnote{\url{https://github.com/Zubax/Komar}}.
```suggestion
itself for best performance. Komar is based on \mbox{mitochondrik} control module. All hardware is open source and available on Github\footnote{\url{https://github.com/Zubax/Komar}}.
```

2020-04-14 11:12 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +\input{mechanical characteristics}
+

2020-04-14 11:12 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +\input{motor selection}
+

2020-04-14 11:13 UTC, j3qq4hch commented on docs/datasheet/communication interfaces.tex
> +	2       & Input/Output & GPIO1     & RC PWM input/Thermistor input\\
Вы просите добавить ПРОБЕЛ?

2020-04-14 11:15 UTC, j3qq4hch commented on docs/datasheet/communication interfaces.tex
> +    CAN1 (2 connectors)     & JST SM04B-GHS     \\
Вы правы. Починено

2020-04-14 11:16 UTC, j3qq4hch commented on docs/datasheet/overview.tex
> +12 –- 51 V (4 –- 12S $\text{LiCoO}_\text{2}$ battery).
+

2020-04-14 11:17 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> + any PMSM or BLDC motor as it is able to measure the parameters of the driven motor and automatically optimize
+

2020-04-14 11:17 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> + itself for best performance. Komar is based on \mbox{mitochondrik} control module. All hardware is open source and available on Github\footnote{\url{https://github.com/Zubax/Komar}}.
+

2020-04-14 11:21 UTC, j3qq4hch commented on docs/datasheet/mechanical characteristics.tex
> +
GOTOVO

2020-04-14 16:23 UTC, dimracer commented on docs/datasheet/communication interfaces.tex
> +	2       & Input/Output & GPIO1     & RC PWM input/Thermistor input\\
да

2020-04-14 16:34 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +\input{led indication}
устарело

2020-04-14 16:35 UTC, j3qq4hch commented on docs/datasheet/characteristics.tex
> +If the self-resistance of the power supply network is not sufficiently low, the regenerative energy transfer may lead to an increase of the supply voltage beyond the safe operating limits.
устарело

2020-04-14 16:36 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
тут и не написано про мотор

2020-04-14 16:36 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +         Myxa B offers a doubly-redundant CAN bus interface for mission-critical applications.
+

2020-04-14 16:37 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +\includegraphics[width=0.6\textwidth]{figures/top view.png}
Фото очень плохие и корпуса не того цвета. Поменяем позднее, когда и если правильный корпус будет изготовлен

2020-04-14 16:37 UTC, dimracer commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
Тут написано про преднастройку под определенный мотор.

2020-04-14 16:38 UTC, dimracer commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
Это было взято из Sadulli. Тут этот пункт следует просто убрать.

2020-04-14 16:41 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +    \item 12 -- 51 V input voltage range (4 -- 12S $\text{LiCoO}_\text{2}$ battery).
+

2020-04-14 16:42 UTC, j3qq4hch commented on docs/datasheet/characteristics.tex
> +    DC continuous current     &       & 90              &   A            \\
+

2020-04-14 16:42 UTC, j3qq4hch commented on docs/datasheet/characteristics.tex
> +    Supply voltage                          & 12    &       & 51    & V               \\
+

2020-04-14 16:42 UTC, j3qq4hch commented on docs/datasheet/characteristics.tex
> +    Phase current amplitude   &       & 130\tnote{a}    &   A            \\
+

2020-04-14 16:43 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
Это скопировано из мухи.

2020-04-14 16:44 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
но ведь ТЕХНИЧЕСКИ часть параметров там и правда может быть ПРЕДНАСТРОЕНА.

2020-04-16 16:33 UTC, dimracer requested changes

2020-04-16 16:33 UTC, dimracer commented on docs/datasheet/mechanical_characteristics.tex
> +    \includegraphics[width=0.7\textwidth]{mechanical_drawing.pdf}
Нет такого файла.
Пожалуйста, проверяйте, что проект компилируется без ошибок, прежде чем отправлять на review.

2020-04-16 18:32 UTC, dimracer commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
Значит, в мухе тоже это следует исправить. Никакой преднастройки на high dynamic response and high-efficiency operation нет и быть не может, если мотора нет. Не следует вводить пользователя в заблуждение. И пожалуйста, не закрывайте комментарий, если он не исправлен.

2020-04-16 18:38 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\includegraphics[width=0.6\textwidth]{figures/top view.png}
Хорошо, давайте оставим эти картинки и добавим фото. Без фото реального изделия даташит смотрится как реклама прототипа.

2020-04-16 18:38 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\includegraphics[width=0.6\textwidth]{figures/top view.png}
Хотя бы одну фотокарточку добавим.

2020-04-16 22:27 UTC, j3qq4hch commented on docs/datasheet/mechanical_characteristics.tex
> +    \includegraphics[width=0.7\textwidth]{mechanical_drawing.pdf}
и правда, он потерялся. Теперь он на месте

2020-04-17 16:16 UTC, j3qq4hch commented
GOTOVO

2020-04-17 16:17 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +    \item Ready right out of the box, all parameters are pre-tuned for high dynamic response and high-efficiency operation.
+

2020-04-18 12:54 UTC, dimracer commented on docs/datasheet/Komar.tex
> +\includegraphics[width=0.6\textwidth]{figures/top view.png}
@j3qq4hch @pavel-kirienko что насчет фото?

2020-04-18 13:03 UTC, dimracer requested changes

2020-04-18 13:03 UTC, dimracer commented on docs/datasheet/overview.tex
> +12 -- 51 V (4 -- 12S $\text{LiCoO}_\text{2}$ battery).
```suggestion
\mbox{12 -- 51 V} (4 -- 12S $\text{LiCoO}_\text{2}$ battery).
```

2020-04-21 11:43 UTC, j3qq4hch commented
all resolved

2020-04-23 20:48 UTC, merged