erc warnings
Zubax/Komar pull request #29
Opened 2021-08-01 09:09 UTC by dimracer

Before we release the manufacturing documentation and generate gerbers, all the DRC and ERC errors should be resolved and all the warnings should be checked and acknowledged.

2021-08-01 17:16 UTC, pavel-kirienko requested changes
@dimracer you need to erase the two non-compliant commits from the master branch first. Please remember that the only way to introduce changes into a released product is by sending a pull request. Pushing to master is not okay.

2021-08-01 17:29 UTC, dimracer commented
I've revert the commit in the master branch already

2021-08-01 17:31 UTC, pavel-kirienko commented
I see that now, okay.

2021-08-01 17:56 UTC, pavel-kirienko approved these changes

2021-08-03 11:37 UTC, farzan-saleem approved these changes

2021-08-03 11:37 UTC, merged