changed R7
Zubax/Komar pull request #40
Opened 2023-01-04 11:00 UTC by Zentrus

changed R7 from ERJ-2RKF1501X to ERJ-PA2F1602X.

2023-01-04 11:06 UTC, pavel-kirienko requested changes
Please add a new entry in the changelog for the next minor version.

2023-01-04 11:28 UTC, pavel-kirienko approved these changes

2023-01-06 11:59 UTC, suzonch approved these changes

2023-01-06 12:02 UTC, pavel-kirienko approved these changes
LGTM

2023-01-06 12:02 UTC, merged