Copy edits (1st pass)
Zubax/Komar pull request #5
Opened 2020-05-01 15:21 UTC by clyde-johnston

I have used the same text as Myxa wherever possible.  Please review.

2020-05-05 10:11 UTC, dimracer requested changes

2020-05-05 10:11 UTC, dimracer commented on docs/datasheet/Komar.tex
> +measures the motor parameters to optimize its own performance. Komar is based on the Mitochondrik control module,
should be the same as in the Myxa datasheet.

2020-05-05 10:11 UTC, dimracer commented on docs/datasheet/overview.tex
> +Myxa does, however, offer a power delivery feature that when enabled will deliver 5\,V to the power
```suggestion
Komar does, however, offer a power delivery feature that when enabled will deliver 5\,V to the power
```

2020-05-06 23:01 UTC, clyde-johnston commented on docs/datasheet/Komar.tex
> +measures the motor parameters to optimize its own performance. Komar is based on the Mitochondrik control module,
I understood that Komar does not have an accessible UART interface, so I have removed this. Is this correct?

2020-05-06 23:02 UTC, clyde-johnston commented on docs/datasheet/Komar.tex
> +measures the motor parameters to optimize its own performance. Komar is based on the Mitochondrik control module,
Komar has this additional sentence:
>  Komar is based on the Mitochondrik control module, the hardware design of which is open source and available on Github.

Does this apply to Myxa too?  Or is this unique to Komar?

2020-05-06 23:05 UTC, clyde-johnston commented on docs/datasheet/Komar.tex
> +measures the motor parameters to optimize its own performance. Komar is based on the Mitochondrik control module,
Under "Applications"
> CMG drives for LEO spacecraft
Can Myxa be used for CMG drives? Should we mention this in addition to UAVs, UUVs and USVs in the "Overview" paragraph?

2020-05-07 06:50 UTC, j3qq4hch commented on docs/datasheet/Komar.tex
> +measures the motor parameters to optimize its own performance. Komar is based on the Mitochondrik control module,
> Komar has this additional sentence:
> 
> > Komar is based on the Mitochondrik control module, the hardware design of which is open source and available on Github.
> 
> Does this apply to Myxa too? Or is this unique to Komar?

This is unique to Komar.



> I understood that Komar does not have an accessible UART interface, so I have removed this. Is this correct?

This is correct

2020-05-07 10:18 UTC, clyde-johnston commented
Closing pull request.  I will open a new one with the next commit.

2020-05-07 10:18 UTC, closed without merging