V 0.3
Zubax/Komar pull request #8
Opened 2020-05-05 14:13 UTC by j3qq4hch

Перед запуском в производство новой партии плат я решил внести несколько изменений в проект. Плата не поменялась никак, поменялись только некоторые компоненты:
* Шунты стали 1.5 мОм вместо 1
* TVS диод заменен на другой, с Vreverse = 51 V, был 53 V. Теперь он будет срабатывать немного раньше, что хорошо
* Защита от превышения фазного тока была настроена на ~130 A резистором на 1 КОм на пине 'OC_ADJ'. Резистор заменен на 1.5 КОм, что дает уровень срабатывания защиты ~200 A
* Электролитические конденсаторы заменены на более крупные с бОльшей емкостью. Было 220 мкФ, стало 330 мкФ.

2020-05-06 01:13 UTC, dimracer requested changes
1. **Шунты.** Если я правильно понимаю, выбор компонентов был основан на расчетах в таблице https://docs.google.com/spreadsheets/d/1axGHQfVU-xP3OTxVYLaaQBSNWgYnpkbbmnyLpejNwkY/edit#gid=0
Для мотор-контроллеров, как известно, в документации приводят максимальную продолжительную мощность и максимальную пиковую мощность или ток. Выбор шунтов должен производиться для максимального пикового тока. В таблице же расчет произведен для стационарного режима. Если мы нормируем максимальный пиковый ток в даташите на уровне 100 А, то нужно и шунт на этот ток подбирать. При этом должны выполняться два условия. 
* Амплитуда напряжения на токе 100 А должна укладываться в диапазон входного напряжения усилителей (0.3 В). Это условие выполняется.
* Максимальная выделяемая мощность на максимальном пиковом токе за 10 сек не должна быть превышена. Действующее значение тока через резистор равно 100/sqrt(2) = 70.7 A. Резисторы обладают довольно малой теплоемкостью, и при превышении номинальной мощности довольно быстро перегреваются. В перспективе это может привести к непредсказуемому выходу их из строя. Для резисторов нормируется максимальная энергия или мощность импульса от времени. Есть специальные калькуляторы. http://www.vishay.com/resistors/power-metal-strip-calculator/
Так, например, если взять WLSP2512 и сопротивление 0.0015 Ом, то в течение 10 сек на резисторе будет выделяться 7.35 Вт мощности. По графику определяем, что при нормальной температуре окружающей среды максимальная мощность при такой продолжительности импульса составляет 7.5 Вт, укладываемся.
![image](https://user-images.githubusercontent.com/11502518/81129977-c8f5e280-8f4e-11ea-99f8-cbf6c9270aa8.png)
Однако, если возьмем WSK2512, то максимальная мощность составит всего 2.5Вт
![image](https://user-images.githubusercontent.com/11502518/81130057-0eb2ab00-8f4f-11ea-8a50-dca1e7658cd8.png)
В даташите на выбранные резисторы CSR2512C0R0015F не дается эта нормировочная характеристика. Там лишь указывается одна точка - 5 кратное превышение мощности при 5 сек длительности импульса. Возможно эти резисторы имеют схожие характеристики с WLSP2512. Но я бы все же сделал выбор в сторону последних, т.к. для них есть мощностные графики, и они AEQ-200 grade. 
Расчеты в таблице следует скорректировать, иначе потом для более мощных контроллеров они точно приведут к ошибке выбора.

2020-05-06 11:09 UTC, j3qq4hch commented
Ок, резисторы меняются на [WSLP25121L500FEA](https://www.digikey.com/product-detail/en/vishay-dale/WSLP25121L500FEA/541-10147-6-ND/9758753)

2020-05-06 11:14 UTC, j3qq4hch commented
Единственный доступный резистор от Vishay Dale на текущий момент - [WSLP25121L500FEA](https://www.digikey.com/product-detail/en/vishay-dale/WSLP25121L500FEA/541-10147-6-ND/9758753)
![image](https://user-images.githubusercontent.com/9300016/81170642-b5289b80-8fa3-11ea-8fc4-e74a77f753f3.png)
И хотя он, в отличие от текущего AEC-Q200 совместим, нельзя игнорировать, что его температурный коэффициент более чем в 5 раз выше. 
Я бы хотел воздержаться от такой замены

2020-05-06 11:59 UTC, dimracer commented
В таком случае следует взять [CRE2512-FZ-R001](https://www.digikey.com/product-detail/en/bourns-inc/CRE2512-FZ-R001E-3/CRE2512-FZ-R001E-3CT-ND/4900086). Мы прописали в политиках, что следует выбирать AEQ grade компоненты. Не вижу веских причин выбирать здесь не AEQ grade компонент. Сопротивление лучше оставить 0.001 Ом. Это, конечно, уменьшит разрешающую способность измерения тока, но, как мы уже убедились, опенмуха при этом прекрасно работала. Зато меньшее сопротивление снизит потери (хоть и незначительно, но мы тут за каждый ватт боремся) и даст небольшой запас по максимальной мощности резистора, что позволит продлить срок его службы.

2020-05-06 12:01 UTC, j3qq4hch commented
Идея этой замены как раз и заключается в улучшении измерения тока.

2020-05-06 12:01 UTC, dimracer commented
Ну так вот она не обоснована в данном случае.

2020-05-06 12:12 UTC, dimracer commented
2. **TVS диод**. Более низкое напряжение срабатывания вполне оправдано. Только следует все же выбрать AEQ grade компонент. Например, [SMC5K51A-M3/I](https://www.digikey.com/product-detail/en/vishay-semiconductor-diodes-division/SMC5K51A-M3-I/SMC5K51A-M3-IGICT-ND/7427270).

2020-05-06 12:13 UTC, j3qq4hch commented
С шунтом 1.5 мОм используется 90% динамического диапазона измерения тока
С шунтом 1.5 мОм используется 60% динамического диапазона измерения тока
Вы предлагаете пожертвовать 30% динамического диапазона для совместимости с AEC-Q?

2020-05-06 12:21 UTC, dimracer commented
> С шунтом 1.5 мОм используется 90% динамического диапазона измерения тока
> С шунтом 1.5 мОм используется 60% динамического диапазона измерения тока
> Вы предлагаете пожертвовать 30% динамического диапазона для совместимости с AEC-Q?

В данном случае следует пожертвовать в пользу надежности и меньших потерь. Если говорить о мощных контроллерах (на 20 кВт и выше), в которых используются шунты, то там действительно значительно проявляется шум измерения тока из-за слишком малых значений сопротивления шунта. На опенмухе с 1 мОм шунтом я этого не заметил. Поэтому это не критично.

2020-05-06 12:22 UTC, dimracer commented
3. **Конденсатор**. По конденсатору у меня замечаний нет.

2020-05-06 13:09 UTC, j3qq4hch commented
Новые конденсаторы все-таки принесли с собой затруднения. В случае, если комар все-таки будет когда-нибудь использован как часть интегрированного привода и если крепление мотора будет осуществляться винтами М4, то не получится использовать произвольные винты. Только [низкопрофильные](https://www.mcmaster.com/92855a408) или с [полукруглой головкой](https://www.mcmaster.com/93310a805)

2020-05-06 19:25 UTC, pavel-kirienko requested changes
Александр, перечитайте политики ещё раз, затем приведите проект в соответствие с ними, как вам уже указал Дмитрий. Все компоненты должны соответствовать AEC-Q. Исключения должны быть явно задокументированы и обоснованы. Вы отклоняетесь от этих требований абсолютно безосновательно. Обновите описание и рендеры в README.

2020-05-07 07:27 UTC, dimracer commented
> Новые конденсаторы все-таки принесли с собой затруднения. В случае, если комар все-таки будет когда-нибудь использован как часть интегрированного привода и если крепление мотора будет осуществляться винтами М4, то не получится использовать произвольные винты. Только [низкопрофильные](https://www.mcmaster.com/92855a408) или с [полукруглой головкой](https://www.mcmaster.com/93310a805)

Давайте выберем еще конденсатор меньшей емкостью и диаметром и внесем его в BOM как альтернативный вариант.

2020-05-07 07:30 UTC, j3qq4hch commented
Винтов с полукруглой головкой вокруг навалом. Нет смысла уменьшать емкость.

2020-05-07 07:33 UTC, dimracer commented
> Винтов с полукруглой головкой вокруг навалом. Нет смысла уменьшать емкость.
Тем не менее, альтернативный вариант в BOM никому не помешает.

2020-05-08 10:57 UTC, j3qq4hch commented
На текущий момент в проекте не осталось ни одного не AEC-Q совместимого компонента, кроме тех, для которых не нашлось аналогов и транзисторов. 
**Политики** вынуждают меня заменить и транзисторы, т.к. текущие [BSC040N08NS5ATMA1](https://www.digikey.com/products/en?keywords=BSC040N08NS5ATMA1CT-ND) хотя и обладают весьма выдающимися характеристиками, не отвечают критериям AEC Q101.
Единственная разумная замена, которую можно найти на digikey, является  [FDMS86368-F085](https://www.digikey.com/product-detail/en/on-semiconductor/FDMS86368-F085/FDMS86368-F085CT-ND/5254195)
У него выше Rdson, он значительно медленнее (но в комаре мы можем использовать такие на пределе возможностей митохондрика) и скорее всего придется немного изменить футпринты, т.к. корпуса 8-PowerTDFN у всех производителей отличаются в мелочах. 

Нужна ли такая замена?

2020-05-08 12:16 UTC, dimracer commented
> На текущий момент в проекте не осталось ни одного не AEC-Q совместимого компонента, кроме тех, для которых не нашлось аналогов и транзисторов.
> **Политики** вынуждают меня заменить и транзисторы, т.к. текущие [BSC040N08NS5ATMA1](https://www.digikey.com/products/en?keywords=BSC040N08NS5ATMA1CT-ND) хотя и обладают весьма выдающимися характеристиками, не отвечают критериям AEC Q101.
> 
> Единственная разумная замена, которую можно найти на digikey, является [FDMS86368-F085](https://www.digikey.com/product-detail/en/on-semiconductor/FDMS86368-F085/FDMS86368-F085CT-ND/5254195).
> Он отвечает критериям AEC Q101, однако, у него выше Rdson, он значительно медленнее (но в комаре его возможно использовать на пределе возможностей митохондрика) и скорее всего придется немного изменить футпринты, т.к. корпуса 8-PowerTDFN у всех производителей отличаются в мелочах.
> 
> Нужна ли такая замена?

Сопротивление канала на номинальном токе у них обоих 3.5 - 3.7 мОм. Учитывая то, что они будут включены в параллель, очевидно будут перекосы. Следовательно, равновесное сопротивление будет определяться не тем, что прописано в статических характеристиках даташита, а зависимостью от температуры. Зависимость от температуры, если честно, я в даташитах не нашел. Но подозреваю, что она будет примерно одинаковой. А значит, и статические потери будут примерно одинаковыми. 
Входная емкость действительно различается.  Но это совсем не беда. Можно вернуть скорость включения путем пропорционального уменьшения резисторов затворов. Однако я бы не стал уменьшать пропорционально, потому что, как мы уже выяснили, бед от звона значительно больше, чем от нагрева. Можно уменьшить например на 15%. А дальше поэкспериментируем в лаборатории. 
Тепловые характеристики у них одинаковые, что вполне логично, т.к. корпуса одинаковые.
Но вот что очень важно, так это то, что FDMS86368 рассчитан на более высокую температуру  (175С) по сравнения с BSC040N08NS5ATMA1 (150С). С виду разница не заметна, однако на практике это дает большое преимущество по надежности при параллельном включении транзисторов (испытания на мощном контроллере показывали разницу в температурах более чем на 60С, т.е. если один кристалл нагрет до 100, то другой в связке может нагреваться запросто до 160 С).  Поэтому собственно FDMS86368 и AEC-Q101. 
Ну и, как следствие, FDMS86368 способен рассеять большую мощность (хотя это нам не так важно в данном случае, перегрузок таких не будет). 
Поэтому однозначно транзисторы заменяем.

2020-05-08 12:23 UTC, dimracer commented
@j3qq4hch я хочу обратить ваше внимание еще вот на этот тикет https://github.com/Zubax/telega/issues/438
А конкретно на это:
>Тепловые тесты. При нагрузке свыше 2 кВт температура VSI достигает 70-75 С, что вполне допустимо.
По поверхности нижней крышки градиент температуры не более 10 градусов. А вот по поверхности платы значительно больше. В последующих разработках это надо учесть и ставить транзисторы не линейно, а треугольником.

Расположите, пожалуйста, транзисторы треугольником.

2020-05-08 17:01 UTC, j3qq4hch commented
Сейчас в проекте не осталось случайных не AEC-Q компонентов. 
На BOM можно взглянуть здесь https://docs.google.com/spreadsheets/d/1JfokTGy7UqjMSu-3vH-KqhXVTRTuDvTGNOM1J73PyXc/edit?usp=sharing

2020-05-09 21:00 UTC, dimracer commented
Предлагаю заменить TJA1051ATK/3/0Z на TJA1051TK/3,118, т.к. последние продаются поштучно, а не в партии по 6000 шт
Больше к BOM замечаний нет. 
Сообщите, когда разводку можно будет посмотреть.

2020-05-09 21:01 UTC, j3qq4hch commented
сейчас

2020-05-09 21:39 UTC, dimracer commented
при открытии проекта у меня выскочило вот это окно с предупреждениями
![image](https://user-images.githubusercontent.com/11502518/81485577-a4538080-9256-11ea-989a-6ef751b683f6.png)
Не знаю, насколько они критичны. Но можно ли их как-то убрать?

2020-05-10 11:49 UTC, j3qq4hch commented
Можно. Обновите своего орла до последней версии.

2020-05-11 12:11 UTC, dimracer commented
Номинал шунта не поменялся.
![image](https://user-images.githubusercontent.com/11502518/81560281-c0136f80-9399-11ea-9f87-57e8a431c376.png)

2020-05-11 12:30 UTC, dimracer commented
Возможно я конечно придираюсь, но вот этот переход цепи VBUS на слой Top режет глаз. А ведь его можно избежать, если немного подвинуть компоненты.
![image](https://user-images.githubusercontent.com/11502518/81561782-66f90b00-939c-11ea-9de3-a7218548eab7.png)

2020-05-11 17:50 UTC, dimracer commented
По результатам созвона в плату следует внести следующие изменения:
- [ ] Убрать разъем СON8, т.к. этот разъем "выползает" на область, прижимаемую корпусом. В то же время в этом контроллере нет большой надобности в UART. На больших мощностях он неработоспособен. 
- [ ] Заменить название платы на слое Top на 'Komar v0.3'.
- [ ] Попытаться развести затворные цепи параллельно вклюенных транзисторов так, чтобы они не создавали колебательных контуров, т.е. максимально близко друг ко другу.

2020-05-12 08:54 UTC, j3qq4hch commented
я еще раз осмотрел модель. CON8 ничему не мешает. Пусть остается

2020-05-12 10:53 UTC, pavel-kirienko requested changes
Скопирую сюда из слака, чтобы обсуждение было в одном месте:

- [x] Судя по модели, пины USB мешают ли установке митохондрика:

![image](https://user-images.githubusercontent.com/3298404/81674631-2a89e580-9456-11ea-9c52-dc02e9bf3cdd.png)

- [x] Нет ли потребности в тестпадах для автоматизации тестирования до установки митохондрика? Ценность их, конечно, сейчас мала, но и установка ничего не стоит.

- [x] Кажется, проект ссылается на лишние библиотеки:

![image](https://user-images.githubusercontent.com/3298404/81675741-e8fa3a00-9457-11ea-905f-76a10afb71bf.png)

- [x] Отсутствует сборочная документация.

2020-05-12 10:54 UTC, j3qq4hch commented
Разве сборочной документации место в репозитории?

2020-05-12 10:55 UTC, j3qq4hch commented
Дополнительные тестпады не нужны. Сам футпринт митохондрика уже является набором таких тестпадов

2020-05-12 10:58 UTC, pavel-kirienko commented
> Разве сборочной документации место в репозитории?

Разумеется. Документация должна быть размещена вблизи субъекта документирования:

> Internal documentation shall be kept close to the subject of documentation (e.g., in the same version control system repository).

2020-05-12 11:02 UTC, j3qq4hch commented
Я могу прикрепить ее к релизу

2020-05-12 11:04 UTC, pavel-kirienko commented
> Я могу прикрепить ее к релизу

Конечно, это тоже надо сделать. Но сборочная документация включает в себя не только экспорт BOM и герберы, но и текст, чьи исходники следует хранить тут, в репозитории. Я предлагаю просто написать в markdown и экспортировать его в PDF, например (формат может быть любым).

2020-05-12 11:16 UTC, dimracer commented
Я бы отодвинул вот эти конденсаторы ещё сколько это возможно от краев платы. Иначе остается риск касания корпуса припоем. 
![image](https://user-images.githubusercontent.com/11502518/81679568-fbc23e00-945a-11ea-8f8d-a5730fe486a3.png)
![image](https://user-images.githubusercontent.com/11502518/81679724-1b596680-945b-11ea-85bc-415a4349d31d.png)

2020-05-12 11:24 UTC, dimracer commented
- [ ] Исправить DRC
![image](https://user-images.githubusercontent.com/11502518/81680719-3a0c2d00-945c-11ea-8665-559a906a31ff.png)

2020-05-12 11:41 UTC, j3qq4hch commented
>> Судя по модели, пины USB мешают ли установке митохондрика:

USB не мешает установить митохондрик. Откусывать тоже ничего не требуется. 

>> Кажется, проект ссылается на лишние библиотеки

Теперь не ссылается.

2020-05-12 11:43 UTC, j3qq4hch commented
>Я бы отодвинул вот эти конденсаторы ещё сколько это возможно от краев платы. Иначе остается риск касания корпуса припоем.
К примеру, можно транзистор Q5 придвинуть к транзистору Q7. тогда конденсатор С35 прекрасно разместится рядом с Q5.

Я смотрю на модель и не вижу никакого способа что-нибудь закоротить. Расстояние вполне достаточное. Однако, я бы предложил их вовсе не монтировать из других соображений. Батарея керамических конденсаторов кажется несколько избыточной (и излишне дорогой). Вероятно, ее можно сократить в два раза без негативных последствий.

2020-05-12 11:45 UTC, j3qq4hch commented
>>Исправить DRC
Важно ничего не двигать даже чуть-чуть, чтобы DRC не решило, что утвержденные нарушения можно опять показывать. 
У меня нарушений нет:
![image](https://user-images.githubusercontent.com/9300016/81683743-0da5e000-945f-11ea-98c1-76de7d5726e2.png)

2020-05-12 11:47 UTC, dimracer commented
> > Я бы отодвинул вот эти конденсаторы ещё сколько это возможно от краев платы. Иначе остается риск касания корпуса припоем.
> > К примеру, можно транзистор Q5 придвинуть к транзистору Q7. тогда конденсатор С35 прекрасно разместится рядом с Q5.
> 
> Я смотрю на модель и не вижу никакого способа что-нибудь закоротить. Расстояние вполне достаточное. Однако, я бы предложил их вовсе не монтировать из других соображений. Батарея керамических конденсаторов кажется несколько избыточной (и излишне дорогой). Вероятно, ее можно сократить в два раза без негативных последствий.

Почему в 2 раза?
Ок. Давайте вовсе уберем эти 2 конденсатора.

2020-05-12 12:02 UTC, pavel-kirienko commented
> USB не мешает установить митохондрик. Откусывать тоже ничего не требуется.

Ваше утверждение не соответствует модели. Либо вы ошибаетесь, либо модель требует доработки. Вы не можете ошибаться, поэтому, пожалуйста, исправьте модель.

2020-05-12 12:44 UTC, dimracer commented
Я  предложил убрать совсем эти два конденсатора C32 и C35. Оставлять на плате пустые места на силовых шинах, не покрытые маской крайне не желательно.

2020-05-12 12:53 UTC, j3qq4hch commented
Плата будет покрыта лаком, все нормально

2020-05-12 12:55 UTC, dimracer commented
И все же я не вижу надобности оставлять эти конденсаторы. Выпускать плату с большим количеством DNM компонентов - не слишком хорошая практика.

2020-05-12 12:57 UTC, j3qq4hch commented
Это общепринятая практика. Мы их оставим, они не представляют никакой проблемы, но могут пригодиться (а могут и нет)

2020-05-12 12:58 UTC, dimracer commented
>Это общепринятая практика.
Да, но не в этом случае. Мы точно знаем, что не будем их монтировать.

2020-05-12 13:02 UTC, j3qq4hch commented
> Ваше утверждение не соответствует модели. Либо вы ошибаетесь, либо модель требует доработки. Вы не можете ошибаться, поэтому, пожалуйста, исправьте модель.

Готово

2020-05-12 20:06 UTC, dimracer commented
[ ] Убрать С32 и С35.

2020-05-12 20:45 UTC, pavel-kirienko commented
<sub>
May I suggest we put a little yoba somewhere under the Mitochondrik?

![image](https://user-images.githubusercontent.com/3298404/81743501-69e22180-94aa-11ea-8033-0736ebb54c7b.png)

</sub>

2020-05-13 06:31 UTC, j3qq4hch commented
![Komar PCB v9](https://user-images.githubusercontent.com/9300016/81778997-7db67380-94fc-11ea-84bc-2e13013bd135.png)
YOBA ETO TI?

2020-05-13 10:53 UTC, j3qq4hch commented
За сегодня есть несколько изменений:
- YOBA
- Все светодиоды теперь сгруппированы вместе
- Добавились монтажные отверстия для предполагаемых дополнительных пластиковых деталей. Необязательно, что эти детали будут добавлены, но если получится - мы добавим туда почти нормальные световоды и скобы для поддержки конденсаторов (и все равно потом немного клея)

2020-05-14 14:31 UTC, dimracer commented
- [ ] На слое шелкографии обозначить "ключ" митохондрика. 
- [ ] Заменить конденсаторы С1 и С2 на UPW1J221MPD.

2020-05-15 02:42 UTC, j3qq4hch commented
Komar - проект с открытыми исходниками. В таком проекте не следует без особенных причин использовать не оптимальные компоненты. Общую емкость конденсаторов уменьшать не нужно. Я могу заменить текущие 2 по 330 мкф, но не на 2 по 220, а на 3 по 220 мкф, если вы придумаете где там можно малой кровью разместить еще один конденсатор. Я пока не придумал и настаиваю на том, чтобы все осталось как есть. Если очень нужно, я попрошу сборщика изготовить одно или два устройства с уменьшенными конденсаторами, но это должны быть ОСОБЫЕ устройства, а не референс-дизайн. 
Единственным аргументом против такого могло бы быть нежелание плодить устройства, которые отличаются друг от друга в мелочах, о которых мы непременно забудем. Однако, начиная с этой версии комара, на борту силовой платы появилась память, в которой можно помимо прочего хранить и информацию о конденсаторах. Мы теперь никогда не забудем что и куда ставили.

2020-05-16 10:32 UTC, dimracer approved these changes

2020-05-24 15:18 UTC, pavel-kirienko commented
@j3qq4hch когда будет готова документация и корпус?

2020-06-06 22:12 UTC, dimracer commented
> ![image](https://user-images.githubusercontent.com/11502518/83955425-83814980-a85b-11ea-8304-f84767a5e1bf.png)

Думаю, учитывая тот факт, что в предыдущей версии защита срабатывала уже при 93...96 А, следует написать так:
`- Phase current protection trip level is increased up to 150 Amps. `

2020-06-06 22:20 UTC, pavel-kirienko commented
А ещё лучше просто написать как есть, потому что это всё-таки не конечная документация (пусть она и публичная). Можно прямо сказать, что уровень подняли, но конкретный порог сильно зависит от температуры, параметров транзисторов, погоды на Марсе, и т.п.

2020-06-06 22:36 UTC, dimracer commented
Пользователя будет интересовать больше значение (диапазон значений) тока срабатывания, а не то, от чего он зависит. На самом деле, как уже было отмечено в тикете про тестирование, уровень срабатывания защиты зависит больше всего от шума тока. Реальное значение тока срабатывания будет установлено опытным путем. Сейчас его просто следует "занизить" до 150 А. Этого, я думаю, будет достаточно.

2020-06-06 22:38 UTC, dimracer commented
Линии цепей "съехали". Я это поправил.
![image](https://user-images.githubusercontent.com/11502518/83955781-83834880-a85f-11ea-8294-7d04563c2f20.png)

2020-06-06 23:30 UTC, dimracer requested changes

2020-06-06 23:30 UTC, dimracer commented on README.md
> +* YOBA silkscreen logo added.
Этот пункт скорее всего вызовет кучу вопросов пользователей и может привести к недопониманию. Давайте его уберем.

2020-06-06 23:30 UTC, dimracer commented on README.md
> +* Overcurrent protection trip level increased 1.5 times to around 200 A.
ток срабатывания защиты 150 А.

2020-06-06 23:30 UTC, dimracer commented on README.md
> +* Maximum phase current 100 A.
Для переменного тока обязательно следует уточнять RMS или Amplitude. 
В данном случае 
Maximum continuous phase current amplitude - 100 A.

2020-06-06 23:30 UTC, dimracer commented on manufacturing/readme.md
> +The PCB is 4 layer PCB with 1 oz copper on all layers. Its dimensions is a circle with a diameter of 58 mm. PCB Total thickness is 1.58 - 1.6 mm. Solder Mask color should be red, silkscreen color - w
```suggestion
The PCB is 4 layer PCB with 35 um copper on all layers. Its dimensions is a circle with a diameter of 58 mm. PCB Total
 thickness is 1.58 - 1.6 mm. Solder Mask color should be red, silkscreen color - white. 
```

2020-06-07 04:58 UTC, pavel-kirienko requested changes

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +
```suggestion
```

Из-за этой пустой строки у вас список рендерится с большими межстрочными интервалами.
<img width="83" alt="image" src="https://user-images.githubusercontent.com/3298404/83960346-7e8abd00-a890-11ea-9120-5f3f4ed6a94d.png">

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +### Komar V0.3
Предлагаю объявить текущую версию v1.0. Релиз же, нет?

Неплохо бы ещё указать год -- 2020.

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +![](pics/Efficiency.png)
Откуда картинка? Следует обозначить КПД конкретно чего тут демонстрируется.

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +* Current: 50 - 80 A
Continuous phase current amplitude?

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +Despite that Komar still can be used as a separate unit. In this case a custom phase connector mounted on the housing may be used to provide motor connections.
```suggestion
Komar can also be used as a separate unit. In this case, a custom phase connector mounted on the housing may be used to provide motor connections.
```

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +Komar itself consists of a power stage PCB with mitochondrik and an aluminum housing (and several plastic parts).
```suggestion
Komar itself consists of a power stage PCB with Mitochondrik and an aluminum housing (and several plastic parts).
```

Неплохо бы настроить редактор, чтобы пробелы удалял автоматически.

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +The housing is kept together using 4 M3.5 screws. Komar mounting is performed using 4 M4 screws. For mounting a motor to the top part of the housing M4 screws should be used.
```suggestion
The housing is kept together with 4x M3.5 screws. Komar is mounted using 4x M4 screws. The motor is mounted onto the top part of the housing with M4 screws.
```

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
У вас отсутствует предыдущая версия. Можно добавить v0.2 и просто сказать, что это первая, указав заодно год выпуска (2019).

2020-06-07 04:58 UTC, pavel-kirienko commented on README.md
> +<img src="pics/blow scheme.png" alt="Komar blow scheme" style="zoom:100%;"/>
1. Пожалуйста, как я писал в тикете про design notes, сделайте чертёж в векторном формате, чтобы можно было его включить в даташит.

2. У вас отсутствует lightpipe на схеме, как я уже раньше говорил.

2020-06-07 04:58 UTC, pavel-kirienko commented on manufacturing/readme.md
> +* AWG (12 and 14 AWG are used in the design)
Давайте-ка использовать СИ https://www.rapidtables.com/calc/wire/awg-to-mm.html

2020-06-07 04:58 UTC, pavel-kirienko commented on manufacturing/readme.md
> +4. copper_bottom_l4
```suggestion
The copper layers are ordered as follows:

1. copper_top_l1
2. copper_inner_l2
3. copper_inner_l3
4. copper_bottom_l4
```

2020-06-07 04:58 UTC, pavel-kirienko commented on manufacturing/readme.md
> +## Zubax Komar power stage manufacturing instructions
```suggestion
# Zubax Komar power stage manufacturing instructions
```

2020-06-07 04:58 UTC, pavel-kirienko commented on manufacturing/readme.md
> +PCB properties:
Вы тут заголовок хотели сделать?

2020-06-07 04:58 UTC, pavel-kirienko commented on manufacturing/readme.md
> +   ### Assembly
```suggestion
## Assembly
```

2020-06-07 04:58 UTC, pavel-kirienko commented on manufacturing/readme.md
> +4. **Conformal coating.** The PCBs should be covered with conformal coating entirely excluding pin headers on the top (CON100, CON101, CON102, CON103, CON104, CON105) and connectors on the bottom sid
- [ ] О приклейке конденсаторов ничего не сказано.
- [ ] Я не нашёл в BOM проводов, клея для конденсаторов, конформного покрытия, винтов и проч.
- [ ] Чертёж из Construction and usage в главном README не помешает привести и в сборочной документации, мне кажется.

2020-06-10 13:04 UTC, j3qq4hch commented on README.md
> +* YOBA silkscreen logo added.
*

2020-06-10 13:06 UTC, j3qq4hch commented on README.md
> +* Overcurrent protection trip level increased 1.5 times to around 200 A.
*

2020-06-10 13:06 UTC, j3qq4hch commented on README.md
> +* Maximum phase current 100 A.
*

2020-06-10 13:08 UTC, j3qq4hch commented on README.md
> +* Current: 50 - 80 A
*

2020-06-10 17:32 UTC, j3qq4hch commented on manufacturing/readme.md
> +4. **Conformal coating.** The PCBs should be covered with conformal coating entirely excluding pin headers on the top (CON100, CON101, CON102, CON103, CON104, CON105) and connectors on the bottom sid
Чертеж мы приводить не станем. Вместо этого я запилю видео по сборке, вставим его.

2020-06-11 09:10 UTC, dimracer commented on README.md
> +### Komar V0.3
Я за Komar v1.0. Только год в самом названии указывать не стоит.  Он будет и так указан в релизе.

2020-06-11 09:26 UTC, dimracer requested changes

2020-06-11 09:26 UTC, dimracer commented on README.md
> +* Continuous phase current amplitude: 50 - 80 A
Так перестраховаться хорошо с одной стороны. Но с другой стороны, сейчас даже самые простые и слабые ESC держат как минимум 60 А DC тока. А мы тут фазный ток 50 А пишем. Да, мы не проводили очень длительных тестов. Но те тесты, что я проводил, показали, что при наличии обдува пропеллером 90 А амплитуды фазного тока он держит. И температура платы при этом не превышает 90 С. Так что я предлагаю все же не занижать характеристики. Иначе мы так ничего не продадим.

2020-06-11 16:22 UTC, j3qq4hch commented on README.md
> +* Continuous phase current amplitude: 50 - 80 A
ок, пусть будет больше.

2020-06-11 16:25 UTC, j3qq4hch commented on manufacturing/readme.md
> +4. **Conformal coating.** The PCBs should be covered with conformal coating entirely excluding pin headers on the top (CON100, CON101, CON102, CON103, CON104, CON105) and connectors on the bottom sid
Я добавил эту короткую видеоинструкцию. Я знаю, что в ней не хватает пояснительного текста и, возможно, пары компонентов: световода и защитной крышки для разъемов. 
Я не уверен насчет того, что эти компоненты могут и должны использоваться. Понять это мы сможем после того, как соберем хотя бы одно устройство живьем. Тогда же и будут добавлены пояснения в видео, т.к. это довольно муторный процесс, который не хочется переделывать.

2020-06-12 23:52 UTC, pavel-kirienko requested changes
В дополнение к моим предыдущим комментариям, которые вы ещё не разрешили.

2020-06-12 23:52 UTC, pavel-kirienko commented on README.md
> +![](pics/Efficiency.png)
Теперь понятно. Не думаю, что график нужен, ведь можно просто сказать, что теоретический потолок ~97%. Долой его.

2020-06-12 23:52 UTC, pavel-kirienko commented on README.md
> +* KV > 180 (assuming 12S battery is used)
```suggestion
* Continuous power: 2.5 kW
* Continuous phase current amplitude: 90 A
* Outer diameter: 80 mm
* KV > 180 (assuming 12S battery is used)
```

2020-06-12 23:52 UTC, pavel-kirienko commented on manufacturing/readme.md
> +| Mounting screws                                              | Are used to mount the assembled Komar in place               | 4 pcs screws 91292A107 from mcmaster.com (M4 DIN 912 6 mm length screws
- BOM не согласуется со сборочной схемой.
- Средняя колонка не нужна, объедините её с Description.
- Если деталь стандартная, не вижу смысла указывать поставщика, это добавляет работы по поддержке и актуализации документации.

2020-06-12 23:52 UTC, pavel-kirienko commented on manufacturing/readme.md
> +   [![Komar housing assembly instruction](http://img.youtube.com/vi/qDjCuD04zwk/0.jpg)](http://www.youtube.com/watch?v=qDjCuD04zwk "Komar housing assembly instruction")
Видео по ссылке, если вы считаете его полезным, нужно переименовать, чтобы было понятно, что речь идёт о версии 1.0.

2020-06-16 12:19 UTC, j3qq4hch commented on README.md
> +![](pics/Efficiency.png)
*

2020-06-16 12:19 UTC, j3qq4hch commented on manufacturing/readme.md
> +PCB properties:
Точно

2020-06-16 12:22 UTC, j3qq4hch commented on manufacturing/readme.md
> +   [![Komar housing assembly instruction](http://img.youtube.com/vi/qDjCuD04zwk/0.jpg)](http://www.youtube.com/watch?v=qDjCuD04zwk "Komar housing assembly instruction")
готово

2020-06-16 12:29 UTC, j3qq4hch commented on manufacturing/readme.md
> +| Mounting screws                                              | Are used to mount the assembled Komar in place               | 4 pcs screws 91292A107 from mcmaster.com (M4 DIN 912 6 mm length screws
Относитесь к упоминанию mcmaster не как к поставщику, а как к странице продукта на digikey, у них очень хороший каталог всех винтиков и гаек на свете. Такой артикул полезен, и удалять его не следует. 
С какой сборочной схемой не согласуется BOM? Что это?

2020-06-16 13:03 UTC, dimracer commented on manufacturing/readme.md
> +| Mounting screws                                              | Are used to mount the assembled Komar in place               | 4 pcs screws 91292A107 from mcmaster.com (M4 DIN 912 6 mm length screws
Я лишь замечу, что в нашем случае "сборочный цех" находится в Эстонии. Потому логичным будет в наших механических изделиях использовать крепеж, который легко достать в Эстонии.

2020-06-16 16:37 UTC, pavel-kirienko commented on README.md
> +* 13 - 51 V input voltage range (4 - 12S LiCoO<sub>2</sub> battery).
Согласно незаконченной документации на Митохондрик, минимальное напряжение 12 V. Почему тут 13?

```suggestion
* 12...51 V input voltage range (4 - 12S LiCoO<sub>2</sub> battery).
```

2020-06-16 16:37 UTC, pavel-kirienko commented on README.md
> +*  A software-controllable 5 V, 0.5 A BEC.
Максимальная нагрузка BEC -- дело тонкое. Нужно либо убрать её упоминание, либо указать реалистичные значения.

```suggestion
* A software-controllable 5 V BEC.
```

2020-06-16 16:37 UTC, pavel-kirienko commented on README.md
> +* Overcurrent protection trip level increased 1.5 times to around 200 A.
Почему вы отметили это выполненным, не изменив при этом текст?

2020-06-16 16:39 UTC, j3qq4hch commented on README.md
> +* 13 - 51 V input voltage range (4 - 12S LiCoO<sub>2</sub> battery).
Вероятно, опечатка

2020-06-16 16:39 UTC, pavel-kirienko requested changes
Я просмотрел изменения до половины, и заметил, что мои комментарии ещё с первого ревью оставлены без внимания. @j3qq4hch пожалуйста, не запрашивайте новое ревью, пока не закончите с предыдущим. Я вернусь когда всё будет готово.

2020-06-17 11:46 UTC, j3qq4hch commented
https://github.com/Zubax/Komar/pull/8#discussion_r440990329
О чем здесь говорится?

2020-06-17 15:44 UTC, pavel-kirienko commented
> Overcurrent protection trip level increased 1.5 times to around 200 A.

Дмитрий писал, что надо указывать 150 А. Если вы не согласны с этим, скажите явно. Если согласны, внесите изменения как предложено.

2020-06-17 15:46 UTC, j3qq4hch commented
> > Overcurrent protection trip level increased 1.5 times to around 200 A.
> 
> Дмитрий писал, что надо указывать 150 А. Если вы не согласны с этим, скажите явно. Если согласны, внесите изменения как предложено.

![image](https://user-images.githubusercontent.com/9300016/84919611-d2847580-b0ca-11ea-99ee-f1e37d7e5ecc.png)
Ровно это уже и написано.

2020-06-17 15:47 UTC, pavel-kirienko commented
Ок.

2020-06-19 12:12 UTC, j3qq4hch commented
> * [ ]  Убрать С32 и С35.
Они помечены как немонтируемые, футпринты остаются.

2020-06-19 12:13 UTC, j3qq4hch commented
> * [x]  На слое шелкографии обозначить "ключ" митохондрика.
> * [ ]  Заменить конденсаторы С1 и С2 на UPW1J221MPD.

Ключ появился. Конденсаторы C1, C2 не будут заменены на UPW1J221MPD в проекте. Они могут быть только отдельно по специальной просьбе заменены на что-то другое в каком-то частном случае(что тоже не рекомендуется).

2020-06-19 12:15 UTC, j3qq4hch commented on manufacturing/readme.md
> +| Mounting screws                                              | Are used to mount the assembled Komar in place               | 4 pcs screws 91292A107 from mcmaster.com (M4 DIN 912 6 mm length screws
Никаких артикулов частных поставщиков крепежа в BOM решено не иметь.

2020-07-06 10:40 UTC, j3qq4hch commented on README.md
> +*  A software-controllable 5 V, 0.5 A BEC.
Текст изменен

2020-07-06 10:56 UTC, j3qq4hch commented on README.md
> +The housing is kept together using 4 M3.5 screws. Komar mounting is performed using 4 M4 screws. For mounting a motor to the top part of the housing M4 screws should be used.
+

2020-07-06 11:00 UTC, j3qq4hch commented on README.md
Ок

2020-07-06 11:22 UTC, j3qq4hch commented on README.md
> +<img src="pics/blow scheme.png" alt="Komar blow scheme" style="zoom:100%;"/>
lightpipe появился на взрыв-схеме платы. 
Чертежи стали в векторном формате.

2020-07-06 11:32 UTC, j3qq4hch commented on manufacturing/readme.md
> +* AWG (12 and 14 AWG are used in the design)
+

2020-07-06 18:54 UTC, pavel-kirienko requested changes
Документация подготовлена недобросовестно. Я исправил, что мог, самостоятельно; в частности, я частично привёл в порядок BOM. Требуется доделать следующее:

- [x] Отразить в BOM различные варианты сборки фазного интерфейса. Возможно, нужно добавить колонку с указанием варианта сборки.

- [x] В BOM отсутствует спецификация кабелей для фазного разъёма (между платой и буллетами); её необходимо внести.

- [x] Отсутствуют инструкции по 3D печати компонентов.

- [x] Отсутствует детальное описание процесса сборки фазного разъёма. Ввиду сложности процедуры, фазный разъём можно вообще описать отдельным документом, и просто сослаться на него из основного BOM как на независимый компонент.

- [x] Нужно указать part number термопрокладки. Сейчас там указан только производитель и толщина.

- [x] Нужно проверить потребное количество клея и конформного покрытия; сейчас я вписал значения на глаз. Для проверки нужно поднять документацию на муху из Oshino.

- [x] Нужно проверить количество термопрокладки.

И ещё, пожалуйста, не забывайте пользоваться граммарли.

Мы будем заниматься наноменеджментом, пока вы не научитесь готовить нормальную документацию.

2020-07-07 11:18 UTC, dimracer commented
- [ ] Не указан P/N шунтовых резисторов. Выше я писал, что следует выбрать  [CRE2512-FZ-R001](https://www.digikey.com/product-detail/en/bourns-inc/CRE2512-FZ-R001E-3/CRE2512-FZ-R001E-3CT-ND/4900086).
![image](https://user-images.githubusercontent.com/11502518/86772456-c30aa380-c05c-11ea-9bc4-ab68c15eb599.png)

2020-07-07 11:22 UTC, j3qq4hch commented
> * [x]  Не указан P/N шунтовых резисторов. Выше я писал, что следует выбрать  [CRE2512-FZ-R001](https://www.digikey.com/product-detail/en/bourns-inc/CRE2512-FZ-R001E-3/CRE2512-FZ-R001E-3CT-ND/4900086).
>   ![image](https://user-images.githubusercontent.com/11502518/86772456-c30aa380-c05c-11ea-9bc4-ab68c15eb599.png)

Он указан. Вы просто не там смотрите.

2020-07-07 12:29 UTC, dimracer commented
Где он указан?

2020-07-07 12:32 UTC, j3qq4hch commented
![image](https://user-images.githubusercontent.com/9300016/86781769-f2bea900-c066-11ea-9e2f-0e519f0116c9.png)
В атрибутах самого компонента(в его свойствах тоже, впрочем), а не в свойствах надписи с рефдезом.

2020-07-08 09:32 UTC, j3qq4hch commented
На данный момент есть только один вариант сборки фазного интерфейс - с фазным разъемом.

2020-07-08 16:57 UTC, dimracer commented
@j3qq4hch добавьте еще, пожалуйста, исправления вскрытия маски на плате в этот же PR.

2020-07-08 19:08 UTC, j3qq4hch commented
> @j3qq4hch добавьте еще, пожалуйста, исправления вскрытия маски на плате в этот же PR.

gotovo

2020-07-09 16:44 UTC, pavel-kirienko commented
@j3qq4hch пожалуйста, уберите колонку с описанием из взрыв-схемы, потому что её содержимое повторяет BOM и частично ему противоречит. Используйте идентичные обозначения компонентов на схемах и в BOM. На схеме общей сборки присутствует какой-то мистический компонент POWER CONNECTOR ASSEMBLY; я не знаю, что это такое, и зачем оно нужно. Вам следует внимательнее проверять результаты своей работы.

2020-07-10 11:07 UTC, j3qq4hch commented
> @j3qq4hch пожалуйста, уберите колонку с описанием из взрыв-схемы, потому что её содержимое повторяет BOM и частично ему противоречит. Используйте идентичные обозначения компонентов на схемах и в BOM. На схеме общей сборки присутствует какой-то мистический компонент POWER CONNECTOR ASSEMBLY; я не знаю, что это такое, и зачем оно нужно. Вам следует внимательнее проверять результаты своей работы.

https://github.com/Zubax/Komar/compare/fbca4a79b448...c9249fbaeb9e

2020-07-11 23:11 UTC, pavel-kirienko commented
Ок. Я исправил BOM, убрав из него винты крепления крышки, что вы забыли сделать, привёл описание в соответствие с BOM, и исправил описание взрыв-схемы (она корректна только для одного из двух вариантов сборки).

Пожалуйста, приведите взрыв-схему в соответствие с BOM:

- 1 шт housing screws set --> 4 шт housing screw
- аналогично motor mount screw & mounting screw
- уберите разрыв в нумерации компонентов, потому что он сбивает с толку -- за пунктом 8 у вас идёт 11

Безотносительно вышеописанного, у меня вопрос к @dimracer : нужны ли в BOM винты крепления мотора к корпусу и корпуса ко внешней структуре? Ведь они не являются частью изделия, но всего лишь входят в комплект поставки. Возможно, есть смысл вынести их из сборочной документации, и просто обозначить их как рекомендуемый комплект поставки? Это ещё и упростит документацию.

2020-07-13 10:08 UTC, j3qq4hch commented
> Ок. Я исправил BOM, убрав из него винты крепления крышки, что вы забыли сделать, привёл описание в соответствие с BOM, и исправил описание взрыв-схемы (она корректна только для одного из двух вариантов сборки).
> 
> Пожалуйста, приведите взрыв-схему в соответствие с BOM:
> 
> * 1 шт housing screws set --> 4 шт housing screw
> * аналогично motor mount screw & mounting screw
> * уберите разрыв в нумерации компонентов, потому что он сбивает с толку -- за пунктом 8 у вас идёт 11
> 
> Безотносительно вышеописанного, у меня вопрос к @dimracer : нужны ли в BOM винты крепления мотора к корпусу и корпуса ко внешней структуре? Ведь они не являются частью изделия, но всего лишь входят в комплект поставки. Возможно, есть смысл вынести их из сборочной документации, и просто обозначить их как рекомендуемый комплект поставки? Это ещё и упростит документацию.

gotovo

2020-07-13 14:40 UTC, dimracer commented
> Ок. Я исправил BOM, убрав из него винты крепления крышки, что вы забыли сделать, привёл описание в соответствие с BOM, и исправил описание взрыв-схемы (она корректна только для одного из двух вариантов сборки).
> 
> Пожалуйста, приведите взрыв-схему в соответствие с BOM:
> 
> * 1 шт housing screws set --> 4 шт housing screw
> * аналогично motor mount screw & mounting screw
> * уберите разрыв в нумерации компонентов, потому что он сбивает с толку -- за пунктом 8 у вас идёт 11
> 
> Безотносительно вышеописанного, у меня вопрос к @dimracer : нужны ли в BOM винты крепления мотора к корпусу и корпуса ко внешней структуре? Ведь они не являются частью изделия, но всего лишь входят в комплект поставки. Возможно, есть смысл вынести их из сборочной документации, и просто обозначить их как рекомендуемый комплект поставки? Это ещё и упростит документацию.

Согласен. Согласно ЕСКД (почти уверен что в ISO так же) каждая структурная единица изделия должна иметь свою документацию. Т.е. Допустим у нас есть изделие `Mitochondrik-LV`, которое имеет комплект схем. герберов, сборочный чертеж и спецификацию (BOM). Он входит в состав изделия допустим `Komar ESC`, которое имеет спецификацию, общую схему (или схему соединениц), сборочный чертеж и спецификацию (BOM). В этой документации, точнее в спецификации, все вышеупомянутые изделия (платы PCB, Mitochondrik LV и т.п. идут с нашим внутренним номером (децимальным номером). По этому номеру можно найти соответственно документацию на каждое изделие. Ну и наконец, изделие, например, `Komar`, которое выставляется у нас в магазине включает в себя упаковку, крепежные элементы для установки на шасси и непосредственно сам `Komar ESC` должно иметь спецификацию, где перечислены все вышеуказанные изделия со своими номерами и компоненты, и "Жук" (схема Э0) при необходимости. 
В нашем случае мы можем сделать проще: выпустить документацию на `Komar ESC`, а на `Komar` привести спецификацию непосредственно в магазине.

2020-07-13 16:49 UTC, j3qq4hch commented
Лишние винтики нас покинули

2020-07-13 19:41 UTC, pavel-kirienko approved these changes

2020-07-13 19:41 UTC, pavel-kirienko commented
@dimracer пожалуйста, проверь и одобри.

2020-07-14 12:13 UTC, dimracer approved these changes

2020-07-14 12:13 UTC, merged