Copy Edits (2nd pass)
Zubax/Komar pull request #9
Opened 2020-05-10 22:45 UTC by clyde-johnston

2020-05-11 22:14 UTC, dimracer requested changes

2020-05-11 22:14 UTC, dimracer commented on docs/datasheet/Komar.tex
> +optimize motor performance by automatically calibrating the motor parameters. Komar is based
optimize motor control performance

2020-05-12 22:42 UTC, dimracer requested changes

2020-05-12 22:42 UTC, dimracer commented on docs/datasheet/communication_interfaces.tex
> +Please note that the CAN bus must be terminated externally since it is not terminated internally by
since it can not be terminated internally by the device.

2020-05-13 09:26 UTC, clyde-johnston commented on docs/datasheet/communication_interfaces.tex
> +Please note that the CAN bus must be terminated externally since it is not terminated internally by
Done

2020-05-13 12:27 UTC, dimracer approved these changes

2020-05-24 15:17 UTC, pavel-kirienko commented
I have submitted a review to Myxa; I suggest transferring relevant changes here as well. Please request another review when done.

2020-06-06 11:41 UTC, j3qq4hch commented
[komar drawings.zip](https://github.com/Zubax/Komar/files/4739904/komar.drawings.zip)
Here is a set of updated graphics for V0.3 of the hardware

2020-06-10 12:47 UTC, pavel-kirienko commented
Closing due to the pending rewrite. Expect a PR later.

2020-06-10 12:47 UTC, closed without merging